### ISSUE TITLE
[QUESTION] Remote Postgres IP

### ISSUE THREAD

**Issue by gr3m1in** [wyatt-herkamp/nitro_repo#518]
Hi

First of all, thank you for this project, it looks very promising 

During local deployment tryouts, i need to specify an ip address of existing postgres instance on the local network.
Grepping the repo, i cannot find the proper way to do so, there is only a hardcoded default with localhost in it...

How can i configure a connection to postgres when it is not at localhost?

Thanks in advance

**Comment by wyatt-herkamp** [comment]
![image](https://github.com/user-attachments/assets/bbc5fd33-06f3-412f-9729-e7032ed2f907)
Does setting 
```toml
[database]
host= ""
``` This should work?

**Comment by gr3m1in** [comment]
Which file should contain this?

**Comment by gr3m1in** [comment]
Oh, this file is not a part of the repo but is generated during installation

https://github.com/wyatt-herkamp/nitro_repo/blob/39032b512a332f00e19fd3c4d5e48f030c76be32/nitro_repo/src/main.rs#L30

and should be modified only after the installation...

https://github.com/wyatt-herkamp/nitro_repo/blob/39032b512a332f00e19fd3c4d5e48f030c76be32/docs/docs/sysAdmin/index.md?plain=1#L20

Ok, i see now
Will try to do it that way
Thanks!

**Comment by wyatt-herkamp** [comment]
> Oh, this file is not a part of the repo but is generated during installation
> 
> https://github.com/wyatt-herkamp/nitro_repo/blob/39032b512a332f00e19fd3c4d5e48f030c76be32/nitro_repo/src/main.rs#L30
> 
> and should be modified only after the installation...
> 
> https://github.com/wyatt-herkamp/nitro_repo/blob/39032b512a332f00e19fd3c4d5e48f030c76be32/docs/docs/sysAdmin/index.md?plain=1#L20
> 
> Ok, i see now Will try to do it that way Thanks!

Yes! I still have the docs from the previous version—just note. I will break the config again because I need to add environment variable support for docker.

Please let me know how testing NR goes. I am always looking for feed back!
